<?php
/**
 * Plugin Name: WP Simple Pay - Modify Customer Record Creation
 * Plugin URI: https://wpsimplepay.com
 * Author: Sandhills Development, LLC
 * Author URI: https://sandhillsdev.com
 * Description: Add custom parameters to the Stripe Customer creation request.
 * Version: 1.0
 */

/**
 * Adds custom parameters to the \Stripe\Customer object creation.
 *
 * @param array                         $customer_args
 * @param SimplePay\Core\Abstracts\Form $form Form instance.
 * @param array                         $form_data Form data generated by the client.
 * @param array                         $form_values Values of named fields in the payment form.
 * @return array
 */
function simpay_custom_add_customer_args_metadata( $customer_args, $form, $form_data, $form_values ) {
	// Add a custom description.
	$customer_args['description'] = 'Customer description.';

	// Add custom metadata.
	$customer_args['metadata']['referral_code'] = '123';

	return $customer_args;
}
add_filter( 'simpay_get_customer_args_from_payment_form_request', 'simpay_custom_add_customer_args_metadata', 10, 4 );
