<?php
/**
 * Plugin Name: WP Simple Pay - Add Payment Metadata
 * Plugin URI: https://wpsimplepay.com
 * Author: Sandhills Development, LLC
 * Author URI: https://sandhillsdev.com
 * Description: Add metadata to a Stripe payment record.
 * Version: 1.0
 */

/**
 * Adds custom metadata to a \Stripe\PaymentIntent record in Stripe.
 *
 * @param array                         $paymentintent_args Arguments for PaymentIntent.
 * @param SimplePay\Core\Abstracts\Form $form Form instance.
 * @param array                         $form_data Form data generated by the client.
 * @param array                         $form_values Values of named fields in the payment form.
 * @param int                           $customer_id Stripe Customer ID.
 * @return array
 */
function simpay_add_custom_payment_metadata( $paymentintent_args, $form, $form_data, $form_values, $customer_id ) {
	// Add metadata with a key of `shirt_color` and a value of "Red".
	$paymentintent_args['metadata']['shirt_color'] = 'Red';

	// Add metadata with a key of `shirt_size` and a value of "Medium".
	$paymentintent_args['metadata']['shirt_size'] = 'Medium';

	return $paymentintent_args;
}
add_filter( 'simpay_get_paymentintent_args_from_payment_form_request', 'simpay_add_custom_payment_metadata', 10, 5 );
