<?php
/**
 * Plugin Name: WP Simple Pay - Custom Item Description
 * Plugin URI: https://wpsimplepay.com
 * Author: Sandhills Development, LLC
 * Author URI: https://sandhillsdev.com
 * Description: Custom item description.
 * Version: 1.0
 */

/**
 * Adjust the PaymentIntent's description with the value of the field with the "Custom Field" Stripe Metadata Label
 *
 * @param array                         $paymentintent_args Arguments for PaymentIntent.
 * @param SimplePay\Core\Abstracts\Form $form Form instance.
 * @param array                         $form_data Form data generated by the client.
 * @param array                         $form_values Values of named fields in the payment form.
 * @return $args
 */
add_filter(
	'simpay_get_paymentintent_args_from_payment_form_request',
	function( $args, $form, $form_data, $form_values ) {
		// Stripe Metadata Label
		$stripe_metadata_label = 'Custom Field';

		$args['description'] = $form_values['simpay_field'][ $stripe_metadata_label ];

		return $args;
	},
	10,
	4
);
